# This file is a part of 'hydroponics' project.
# Copyright (c) 2015, Artyom Lebedev <artyom.lebedev@gmail.com>
# All rights reserved.
# See LICENSE file for copyright details.

import adk

conf = adk.Conf(
    APP_NAME= 'cpu',
    APP_TYPE = 'app',
    PLATFORM = 'avr',
    DEFS = 'SCHEDULER_MAX_TASKS=16 SCHEDULER_CHECK_SLEEPING_ALLOWED=SleepEnabled',
    
    # MCU code name
    MCU = 'atmega328p',
    # Programmer type
    PROGRAMMER = 'avrisp2',
    # Programmer connection
    PROGRAMMER_BUS = '/dev/avrisp',
    # MCU clock frequency in Hz
    MCU_FREQ = 20000000,
    
    # 20MHz low power crystal with maximal startup delay.
    MCU_LFUSE = 0b11111111,
    # Preserve EEPROM on erase.
    MCU_HFUSE = 0b11010111,
    # BOD level 4.3V
    MCU_EFUSE = 0b11111100

    ).Build()
