# This file is a part of 'hydroponics' project.
# Copyright (c) 2015, Artyom Lebedev <artyom.lebedev@gmail.com>
# All rights reserved.
# See COPYING file for copyright details.

import make

conf = make.Conf(SUBDIRS = 'cpu').Build()
